### ISSUE TITLE
3PID invites

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#419] opened 2015-11-24 18:10 UTC
Related: #529

**Comment by Kegsay** [comment] 2015-12-07 16:52
Blocked on https://matrix.org/jira/browse/SYN-540

**Comment by Kegsay** [comment] 2015-12-14 08:56
Background:
 - Client types in https URL for identity server, and client persists it.
 - Client uses this for registration / 3PID linking.
 - This URL cannot be used for 3PID invites.

So I was told to do the same request without `https://` and it Should Work which isn't the most helpful thing ever. This is because HS -> IS traffic is always https so the protocol portion of the URI is redundant/ignored. I don't think clients should be responsible for maintaining two different representations of identity servers just because `https` is "mandated" on HS -> IS; it's a horrible leaky abstraction currently.

In the interest of speed however, I'll just bite the bullet and strip the protocol so this bug can be resolved, but I don't have to like it.

**Comment by Kegsay** [comment] 2015-12-15 15:40
After doing this, I now get `401`d...

**Comment by Kegsay** [comment] 2015-12-15 15:54
Blocked on Synapse working as intended.

**Comment by Kegsay** [comment] 2015-12-15 17:14
So you can now invite users on 3PID if they have already linked their account, but now getting `500`d if they do not have a Matrix account.

**Comment by Kegsay** [comment] 2015-12-15 17:46
So this is now fixed but I'm not getting an email to say I've been invited to a room..

**Comment by Kegsay** [comment] 2015-12-16 09:25
Blocked waiting for invites to send emails.

**Comment by Kegsay** [comment] 2015-12-16 17:59
Need to:
 - Fix https://github.com/vector-im/vector-web/issues/529 - just the new user bit, not the "already have an account so go to settings to bind a new email" for v0.
 - Bind emails on registration on vector (just a flag on the request?)

**Comment by Kegsay** [comment] 2015-12-17 16:55
Fixed mentioned issues. See https://github.com/vector-im/vector-web/issues/529 for follow-on work post-v0.

**Closed by Kegsay** 2015-12-17 16:55 UTC
Labels: bug, p1
