### ISSUE TITLE
peeked preview only gives scrollback up to the point that the room visibility was changed to be peekable?!

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#942] opened 2016-02-16 01:12 UTC
I created a room with shared history (but not world-readable history).  It had content in it.  I changed the shared history to world-readable and tried to peek into the room from a new client.  The peeking operation reliably showed me the history only up to the point that the room was changed to be world-readable - i had to join to see any newer messages(!)

**Comment by richvdh** [comment] 2016-02-17 11:09
Can't reproduce this anywhere, including matrix.org's synapse, and a local v0.13.3.

**Comment by richvdh** [comment] 2016-02-17 13:36
Matthew wasn't able to reproduce this either, though he did find #949. Closing this pending a repro case.

**Closed by richvdh** 2016-02-17 13:36 UTC
Labels: bug, major, p1, release-blocker
