### ISSUE TITLE
New events may cause the timeline to jump up 30-40px after scrolling down

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1162] opened 2016-03-15 18:19 UTC
The jump happens either immediately after you send the message, or in the middle of sending it.

Am trying to repro with scroll debugging enabled.

**Comment by ara4n** [comment] 2016-03-17 02:21
I think this may be related to very tall EventTiles (be they containing images or lots of multi-line stuff) in history.

**Comment by ara4n** [comment] 2016-03-18 17:30
i finally caught this with debug on (but inspector shut). it coincides with the rate-limited logging section.
[barf.txt](https://github.com/vector-im/vector-web/files/180114/barf.txt)

**Comment by richvdh** [comment] 2016-03-19 22:20
So an interesting thing in that barf is that it shows the scroll state is tracking a particular event (`Scrolled to token $1458321036372erwrk:dbkr.me + 59`) rather than being stuck-to-bottom (`Scrolled to bottom`).

That implies that when we last saw a scroll event (17:12:50.011 in the barf), the messagepanel is scrolled up more than 3 pixels from the bottom. I can't really explain why that would have been the case, though

**Comment by ara4n** [comment] 2016-03-19 22:30
hmmmmmm... this is ringing a bell; could this be similar to the bug 
where breakpointing things at the point of fail showed that the whole 
DOM had decided to shrink its height by 50px or so?  I can't remember 
which bug that was or why it was happening though...

**Comment by richvdh** [comment] 2016-03-19 23:01
agreed on all fronts...

**Comment by ara4n** [comment] 2016-03-20 21:38
Just got a classic instance of this, complete with uncensored logging.  I think I even have the right timespan (marked in the log) where it kicked off.  The scrollback suddenly jumped up whilst Erik was typing to me in Internal, and jumped as I pressed the first keystroke in starting a new message. (I wonder if this might be related to the dodgy multi-line-resizing hack that started breaking the other day? https://github.com/matrix-org/matrix-react-sdk/blob/57ffc2d2e26f5f060277c2272b220d85cf096348/src/components/views/rooms/MessageComposer.js#L260)

Barf attached. I think I'll turn off the multi-line resizing on my local develop to see if that helps.

[barf2.txt](https://github.com/vector-im/vector-web/files/181522/barf2.txt)

**Comment by ara4n** [comment] 2016-03-20 21:52
...and again, just after you posted the ALOT img in Internal.  I hadn't turned of multiline resizing yet.

[barf3.txt](https://github.com/vector-im/vector-web/files/181527/barf3.txt)

**Comment by richvdh** [comment] 2016-03-20 22:15
The odd thing in those barfs is all the scroll events (ones that result in 'saved scroll state ...' rather than 'ignoring scroll echo'). Unless you are manually scrolling, we wouldn't expect to see *any* scroll events other than scroll echoes, and their presences reinforces the idea of the DOM reshuffling itself in a way that confuses us.

Looking at my console around the same time, I also see these spurious events, though in my case it ended up sorting itself out, rather than causing a jump.

**Comment by richvdh** [comment] 2016-03-21 14:04
for the record: 
* turning off multi-line resizing didn't help
* @Kegsay observed it this morning in a room with no images at all
* For anybody wanting to follow along at home, a breakpoint at the top of `ScrollPanel._saveScrollState` will help catch the bug in flight. Irritatingly this will also fire when changing rooms or when scrolling manually, so use of ctrl-f8 (deactivate breakpoints) is recommended when trying to scroll manually.

**Comment by richvdh** [comment] 2016-03-21 14:27
With much gratidute to @Kegsay, repro steps are:

* scroll up a bit
* scroll down quite quickly (but not by clicking on the arrow)
* say something (or have someone else say something)

I'm assuming the images were a total red herring, and merely appeared related because you're more likely to scroll up to see what went before if there is an image.

The problem is that we are ignoring the final downward scroll event, because we think it is an echo of our last autoscroll.

**Comment by richvdh** [comment] 2016-03-21 14:27
(you have to scroll down quite quickly, otherwise the penultimate scroll event is close enough to the bottom for us to switch to stuck-to-bottom mode)

**Comment by richvdh** [comment] 2016-03-21 14:56
Hopefully fixed by https://github.com/matrix-org/matrix-react-sdk/issues/237

**Closed by richvdh** 2016-03-21 14:56 UTC
Labels: bug, cosmetic, p1
