### ISSUE TITLE
Random scroll bar in the middle of the timeline

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#1154] opened 2016-03-15 08:53 UTC
I had just refreshed Vector and was going through the rooms. Seem to be happening only in that particular room. And it's stuck at the same place, as if it was a scrollbar inside a bubble.

![capture](https://cloud.githubusercontent.com/assets/8582858/13772281/949ce128-ea93-11e5-9a09-8a233170cccf.PNG)

**Comment by richvdh** [comment] 2016-03-15 09:27
It's caused by that particular message. It is reproducible: you need a plain-text message with a "<space><NL>" sequence in it; Chrome shows the scrollbar when the space doesn't quite fit on the line.

**Comment by richvdh** [comment] 2016-03-15 09:36
It's not a problem in Firefox.

I'd be tempted to whack `overflow-x: hidden` on the relevant class, but @ara4n, as self-appointed CSS-wrangler-in-chief, any other ideas?

**Comment by ara4n** [comment] 2016-03-15 10:39
i'm completely confused as to why that specific tile would be overflowing and can't reproduce here. suggest grabbing me IRL to prod...

**Comment by ara4n** [comment] 2016-03-15 10:57
fixed in cfc4b89

**Closed by ara4n** 2016-03-15 10:57 UTC
