### ISSUE TITLE
Scroll stopped functioning with 'Working around vector-im/vector-web#528'

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1151] opened 2016-03-14 17:43 UTC
I was left able to read and send messages, but unable to scroll - every scroll attempt yielded 'ScrollPanel.js:158 Working around vector-im/vector-web#528'.

Meanwhile the thing didn't think it was scrolled to the bottom, and so every new message reveals a '5 new messages' style prompt, with on way to dismiss it.

I imagine this would be quite easy to repro; i can try again if needed.

<img width="1902" alt="screen shot 2016-03-14 at 17 24 23" src="https://cloud.githubusercontent.com/assets/1294269/13753763/4b050d56-ea0c-11e5-9b30-a41426c499e4.png">

**Comment by ara4n** [comment] 2016-03-14 17:46
(switching room fixed it)

**Comment by richvdh** [comment] 2016-03-14 22:53
Can't repro this, and am struggling to imagine what could have caused it.

Any idea if scroll was working before you closed the search bar? Did you do anything else like resize the window/close the devtools?

**Comment by ara4n** [comment] 2016-03-15 23:10
failing to repro too. i didn't resize or close devtools. i believe scroll was working before i closed the search bar.

**Comment by ara4n** [comment] 2016-03-17 17:10
Just reproduced it again:

<img width="1805" alt="screen shot 2016-03-17 at 17 10 17" src="https://cloud.githubusercontent.com/assets/1294269/13854388/29b93d08-ec63-11e5-8c05-b7461ebcacdd.png">

**Comment by richvdh** [comment] 2016-03-17 17:25
Apparently this time it was nothing to do with search

Could it be something to do with a big message falling off the other end of the timeline?

**Comment by ara4n** [comment] 2016-03-24 14:10
Just got it again on /staging.  Nothing to do with search.  Same symptoms:

`ScrollPanel.js:158 Working around vector-im/vector-web#528` - every time trying to scroll in the room.

Showed it to vdH and it went away on putting the inspector into the main window.

**Comment by richvdh** [comment] 2016-03-29 23:29
I've seen this a bit this evening; in each case it was after clicking the "(v)" jump to bottom button.

What I think happens is:
* We scroll to a particular point in history (either by clicking the "(^) unread messages" bar, or just by scrolling)
* Some updates happen, we do some _restoreSavedScrollStates. At some point we write recentEventScroll, but no scroll event actually happens (presumably because we're up against the end of the scroll), so recentEventScroll stays set. There is no problem for now, because we're close enough to recentEventScroll.
* The user clicks "(v)" and we reload the timeline. The total scroll height is smaller, so scrollTop is smaller than recentEventScroll, and we're stuck.

**Comment by richvdh** [comment] 2016-03-30 08:28
The RoomView gets stuck with `atEndOfLiveTimeline == false`. This suggests that, at the point of the last scroll event, `TimelinePanel.isAtEndOfLiveTimeline()` returned false.

**Comment by richvdh** [comment] 2016-04-01 10:51
I have managed to reproduce this with scrollpanel debugging enabled:
[spew.txt](https://github.com/vector-im/vector-web/files/199434/spew.txt)

It is getting confused about sub-pixel offsets.

**Comment by richvdh** [comment] 2016-04-01 12:23
Steps to repeat:

1. Make sure that the RM is initialised in a room (ie, open it).
1. Make sure that the recent events above the RM have a certain minimum height (multi-line messages, or images)
1. Take vector offline
1. Spam a load of events into the room (at least enough to cause a limited sync on resume, and so that the timelines won't get joined up by pagination. It is important that we have to make network requests to forward-paginate from the RM. 50 seemed too few?).
1. Bring vector back online
1. It now shows "(^) unread messages" bar; click on (^)
 * TimelinePanel resets content to 20 messages before the RM
 * ScrollPanel tries to stay stuck to bottom at this point (`scrollTop=1934` `requested=Number.MAX`), and triggers pagination in both directions (not entirely sure why it decides a back-paginate is necessary)
 * TimelinePanel tells ScrollPanel to put the RM 1/3 down the screen; `scrollTop=1973` `requested=2138.67`
 * Back-pagination completes (we already had these events in memory), scrollpanel resets the scroll; `scrollTop=4101` `requested=4266.67`
 * Scroll event fires with `scrollTop=4101`
 * Top spinner is removed? ScrollPanel resets the scroll. `scrollTop=4034` `requested=4231.67` (not sure why it's 70 pixels shorter at this point rather than 30)
 * Forward-pagination completes, ScrollPanel resets the scroll. `scrollTop=4231` `requested=4231.67`
 * Scroll event fires with `scrollTop=4231`
 * We remove the bottom spinner. ScrollPanel resets the scroll, `scrollTop=4231` `requested=4231.67` and *sets `recentEventScroll`*
 * There is no scroll event because the delta was too small.
1. Click on "(v)" button
 * scroll offset is updated: `scrollTop=1874` `requested=Number.MAX`
1. Because the `scrollTop` is now much smaller than the last `recentEventScroll` (we only have 20 events loaded, as opposed to 40  before, we are now stuck in the workaround code.

There are two problems here:
* we are setting `recentEventScroll` even when the delta is less than 1, so there is no actual scroll event to be expected.  We've been through all this with `_lastSetScroll`
* we aren't resetting `recentEventScroll` in scrollToBottom.

I don't really know why we have a separate `_lastSetScroll` and `recentEventScroll`. We could solve both problems by just using `_lastSetScroll`.

**Comment by richvdh** [comment] 2016-04-05 10:15
This is hopefully fixed by https://github.com/matrix-org/matrix-react-sdk/issues/261

**Closed by richvdh** 2016-04-05 10:15 UTC
Labels: bug, major, p2
