### ISSUE TITLE
[e2e] Blocked user on a device can see message from webclient

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-web#2618] opened 2016-11-21 17:20 UTC
To reproduce:
- From a room with encryption enabled, and 2 users on android clients:
- Invite a user who use the web client
- From this user, accept invitation and block 1 of the users using android client

While the user on android is blocked, he still can see messages from the user on webclient

vector-web version: v0.9.0
(android) version 0.6.1-dev (e951ade)

Please see pictures below to note the problem:
* proof that android user is blocked
![blocked user see my messages part1](https://cloud.githubusercontent.com/assets/22364949/20492898/dff44622-b016-11e6-87fb-b3e3b00f0a92.jpg)
* device informations of the blocked user
![blocked user see my messages part2](https://cloud.githubusercontent.com/assets/22364949/20492916/f50892d4-b016-11e6-8d30-9bf65f92283b.png)
* message from blocker user is visible by blocked user (riotuser6)
![blocked user see my messages part3](https://cloud.githubusercontent.com/assets/22364949/20518666/3e5aa79a-b0a0-11e6-878f-e238d0a76d4f.png)

**Comment by jeangb** [comment] 2016-11-22 10:12
I reproduced this with a simpler case:
- user 1 on iOs client starts a chat with user 2 on WebClient
- user 2 accepts invitation
- user 1 makes room encryption enabled
- user 1 blocks user 2

User 2 can see msgs from user 1 and vice versa.

**Comment by richvdh** [comment] 2016-11-25 10:00
@jeangb: had you already sent a message in the room before blocking? If so, this would be a case of https://github.com/vector-im/vector-web/issues/2146.

If not: I can't reproduce this :/. If you can send me console logs when you send a message from the browser that would help.

**Comment by jeangb** [comment] 2016-11-25 10:54
@richvdh Yes I already sent a message before blocking.
These are the logs: https://gist.github.com/jeangb/ed8f4c6735e0042261708a495770c4a3

FYI the "simplier case" (my first comment of the issue) : I didn't reproduce the bug on Android but I did with iOS.

**Comment by richvdh** [comment] 2016-11-25 10:56
> @richvdh Yes I already sent a message before blocking.

Ok so this sounds like a duplicate of #2146 .

**Closed by richvdh** 2016-11-25 10:56 UTC
Labels: bug, p2, type:e2e
