### ISSUE TITLE
Read marker self-clears even if there is no user activity

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#938] opened 2016-02-16 01:06 UTC
On current develop, the RM auto-disappears immediately after being shown... even if the window has no user activity (mouse movements etc) happening.  We should only be considering messages read (and so RM moving) when the user is actively using the app.  To reproduce, i had two windows side by side scrolled to bottom in the same room, and the read marker appeared and disappeared immediately in the 'backgrounded' receiving window.

**Comment by richvdh** [comment] 2016-02-16 22:35
This sounds a lot like the currently-intended behaviour: RRs from one app will update the RM in the other.

**Comment by ara4n** [comment] 2016-02-17 08:48
I don't believe there was another app generating RRs for that account though.

**Comment by richvdh** [comment] 2016-02-19 15:32
but you had two windows open?

**Comment by ara4n** [comment] 2016-02-19 15:44
I did, one logged in as matthew, the other as matthew2 on my local HS, sending messages back and forth.  There were no other clients.  The RM displayed and then disappeared immediately afterwards on the backgrounded window.  That said, i haven't seen this happen recently, so it may have been fixed?

**Comment by richvdh** [comment] 2016-02-19 16:22
ah, sorry.

hard to see why that would happen unless the app got a spurious activity event. I don't think we've done anything to fix it. <shrug>

**Comment by richvdh** [comment] 2016-02-23 11:14
I'm going to close this for now. Reopen it if you see it again.

**Closed by richvdh** 2016-02-23 11:14 UTC
Labels: bug, minor, p1
