### ISSUE TITLE
List available commands with /help

### ISSUE THREAD

**Issue by sonatagreen** [vector-im/vector-web#546] opened 2015-12-21 02:08 UTC
The slashcommands (e.g. `/join`) are currently not very [discoverable](https://www.experiencedynamics.com/blog/2013/12/ux-power-discoverability). A `/help` command to list the available options would improve this.

**Comment by ara4n** [comment] 2015-12-21 12:19
duplicate of #417.  The good news though is that @kegsay's wiring it up as we speak :)

**Closed by ara4n** 2015-12-21 12:19 UTC
