### ISSUE TITLE
First message ever in a room should be preceded by the Date timestamp bar

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1014] opened 2016-02-25 09:24 UTC
We used to have this but it's got lost, at least for inbound 1:1s

**Comment by richvdh** [comment] 2016-02-26 22:22
I thought it was. this must be a regression.

**Comment by richvdh** [comment] 2016-03-10 14:38
Fixed by https://github.com/matrix-org/matrix-react-sdk/issues/208

**Comment by richvdh** [comment] 2016-03-14 14:15
It's still missing for rooms with short histories.

**Comment by richvdh** [comment] 2016-03-14 14:50
Turns out that the issue for rooms with short histories is mostly due to https://matrix.org/jira/browse/SYN-645

**Comment by richvdh** [comment] 2016-03-14 16:10
Properly fixed by https://github.com/matrix-org/matrix-js-sdk/issues/98

**Closed by richvdh** 2016-03-14 16:10 UTC
Labels: cosmetic, minor, p2
