### ISSUE TITLE
Uncaught Error: getEventTimeline result didn't include requested event

### ISSUE THREAD

**Issue by NegativeMjark** [vector-im/vector-web#861] opened 2016-02-04 13:17 UTC
When switching to a room.

Vector made a context request:
    https://matrix.org/_matrix/client/api/v1/rooms/!DgvjtOljKujDBrxyHk%3Amatrix.org/context/%24145459043587894fTBcT%3Amatrix.org

The requested event was redacted.
[response.json](https://github.com/vector-im/vector-web/files/117442/pretty.txt)

**Comment by richvdh** [comment] 2016-02-16 11:55
This has probably mostly gone away as a result of matrix-org/matrix-react-sdk@8641dab landing, as we no longer attempt to scroll to the read-marker; however we still have the problem if people direct-link to a redacted event.

The problem is basically the same as #901, which is that the timeline code is confused by the fact we remove redacted events from timelines.

**Comment by richvdh** [comment] 2016-02-17 21:42
Hopefully properly fixed now.

**Closed by richvdh** 2016-02-17 21:42 UTC
Labels: bug, minor, p1, release-blocker
