### ISSUE TITLE
self-read-up-to / new messsage indicators sometimes show up even when scrolled to very bottom of chat

### ISSUE THREAD

**Issue by ajohnson23** [vector-im/vector-web#805] opened 2016-01-28 11:40 UTC
Related meta issue: #469

When this strange state occurs, the following oddities can be observed:
* The scrolldown.svg button will display even when i'm scrolled to the very bottom of the chat. Clicking on scrolldown.svg will do nothing, and scrolldown.svg will continue to be shown. Trying to manually scroll down more using the arrow keys or scrollbar does nothing, and scrolldown.svg continues to be shown.
* In this condition, if additional messages arrive to the room, the "n new message(s)" text will show up. Clicking on the "n new message(s)" text sometimes does nothing, and the "n new message(s)" text continues to be shown. Sometimes it works as expected.
* Other oddities that I unfortunately don't recall right now

To reproduce:
* Run:
  https://github.com/matrix-org/matrix-react-sdk 7ea45f9888b89  
  vector 75886c4143faa0  
  https://github.com/matrix-org/matrix-js-sdk 8716185f4a2  
* Go in a room
* Post back-to-back images
* Resize Chrome such that the most recent image is fully visible, but the 2nd most recent image is clipped by the top of the browser window.
* Continue resizing the window bit by bit vertically until you notice the scrolldown.svg show up.
  You may also need to play with turning on the bookmarks bar (Chrome Options > Bookmarks > Show Bookmarks bar). I found that this sometimes made the issue easier to reproduce.

**Comment by ajohnson23** [comment] 2016-01-29 09:18
I probably have a fix for this. I'm testing locally for the next couple days and will see how it goes, and send a PR if it's good.

**Comment by richvdh** [comment] 2016-02-01 10:40
I wasn't able to reproduce this (with or without the bookmarks bar). For the record, this is Chrome 48.0.2564.97, on Linux. I also tried at a couple of different zoom levels.

Nevertheless, I've merged matrix-org/matrix-react-sdk#124, so hopefully it's gone away.

**Closed by richvdh** 2016-02-01 10:40 UTC

**Comment by ajohnson23** [comment] 2016-02-01 11:31
so @richvdh, for the record, I outputted a bunch of debug stuff inside that function when it happens:
```
ScrollPanel.js:163 sn.scrollHeight: 2170
ScrollPanel.js:164 sn.scrollTop: 1690.909054259624
ScrollPanel.js:165 sn.clientHeight: 478
ScrollPanel.js:167 sn.clientHeight + 1: 479
ScrollPanel.js:169 sn.scrollHeight - sn.scrollTop: 479.0909457403759
ScrollPanel.js:171 sn.scrollHeight - sn.scrollTop (479.0909457403759) <= sn.clientHeight + 1 (479)
```

The code used to produce this output:
```
isAtBottom: function() {
var sn = this._getScrollNode();
debuglog("sn.scrollHeight: " + sn.scrollHeight);
debuglog("sn.scrollTop: " + sn.scrollTop);
debuglog("sn.clientHeight: " + sn.clientHeight);
var totalHeight = (sn.clientHeight + 1);
debuglog("sn.clientHeight + 1: " + totalHeight);
var heightMinusTop = sn.scrollHeight - sn.scrollTop;
debuglog("sn.scrollHeight - sn.scrollTop: " + heightMinusTop);
// +1 here to avoid fractional pixel rounding errors
debuglog("sn.scrollHeight - sn.scrollTop (" + heightMinusTop + ") <= sn.clientHeight + 1 (" + totalHeight + ")");
return sn.scrollHeight - sn.scrollTop <= sn.clientHeight + 1;
}
```

While this doesn't necessarily explain why it's happening, at least we know what the values look like when it does happen. Another note, if it's in this messed up state and I click on the scrolldown button, it outputs:
```
Scrolled to bottom; offset now 1690.909054259624
```

**Comment by richvdh** [comment] 2016-02-01 14:13
Ok, thanks for the numbers. Looks like a weirdo Chrome issue to me.
